import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NoInternetWrapper from "@/components/resueable-components/NoInternetWrapper";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* This loader works on the Next.js <Link> component */}
        <NextTopLoader
          color="#25632D"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          zIndex={1600}
        />
        {/* This internet wrapper will only work when there is no internet connection */}
        <NoInternetWrapper>{children}</NoInternetWrapper>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
